site_name: SDS011lib

theme:
  name: material

repo_url: https://github.com/TimOrme/sds011lib

nav:
  - 'index.md'
  - 'understanding.md'
  - 'api_ref.md'
  - 'contributing.md'
  - 'resource.md'

markdown_extensions:
  - admonition
  - pymdownx.superfences

plugins:
- search:
- mkdocstrings:
    default_handler: python
    handlers:
        python:
            options:
                show_source: false