name: PR Checks
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checkpr:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
    steps:
      - uses: actions/checkout@v2
      - name: Setup just
        uses: extractions/setup-just@v1
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install dev dependencies
        run: poetry install --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Check linting
        run: just lint
      - name: Run tox
        run: tox -e py

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install dev dependencies
        run: poetry install --no-root
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Run coverage
        run: pytest --cov-report xml --cov sds011lib/ tests/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3